=== um-dsrg/ASEMI-segmenter/Python/asemi_segmenter/resources/json_schema/tune.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "train.json",
    "definitions": {
        "evaluation_set": {
            "type": "object",
            "properties": {
                "sample_size_per_label": {
                    "type": "integer",
                    "minimum": -1
                },
                "same_as_train": {
                    "type": "boolean"
                }
            },
            "required": ["sample_size_per_label", "same_as_train"],
            "additionalProperties": false
        }
    },
    
    "type": "object",
    "properties": {
        "featuriser": { "$ref": "featuriser.json#" },
        "classifier": { "$ref": "classifier.json#" },
        "training_set": { "$ref": "train.json#definitions/training_set" },
        "evaluation_set": { "$ref": "#definitions/evaluation_set" },
        "tuning": {
            "type": "object",
            "properties": {
                "num_iterations": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        }
    },
    "required": ["featuriser", "classifier", "training_set", "tuning"],
    "additionalProperties": false
}

=== um-dsrg/ASEMI-segmenter/Python/example_volume/tune_config.json
{
    "featuriser": {
        "type": "composite",
        "params": {
                "featuriser_list": [
                    {
                        "type": "voxel",
                        "params": {
                        }
                    },
                    {
                        "type": "histogram",
                        "params": {
                            "radius": { "min": 2, "max": 32 },
                            "scale": 0,
                            "num_bins": { "min": 2, "max": 32 }
                        }
                    },
                    {
                        "type": "histogram",
                        "params": {
                            "radius": { "min": 2, "max": 32 },
                            "scale": { "min": 0, "max": 4 },
                            "num_bins": { "min": 2, "max": 32 }
                        }
                    }
                ]
            }
    },
    "classifier": {
        "type": "random_forest",
        "params": {
            "n_estimators": { "min": 1, "max": 32 },
            "max_depth": { "min": 1, "max": 32 },
            "min_samples_leaf": { "min": 1, "max": 32 }
        }
    },
    "training_set": {
        "sample_size_per_label": 10
    },
    "tuning": {
        "num_iterations": 5
    }
}
